import { GameCategory, GameDefinition, GameType } from '../../../shared/game-types';
import { GameEngine } from './game.definition';

class GameRegistryClass {
  private games: Map<string, GameDefinition> = new Map();
  private engines: Map<string, GameEngine> = new Map();

  constructor() {
    this.registerDefaultDefinitions();
  }

  private registerDefaultDefinitions(): void {
    const list: GameDefinition[] = [
      // ----------------------------------------------------------------------
      // Category A: Core Board Games
      // ----------------------------------------------------------------------
      {
        id: 'TICTACTOE',
        name: 'Tic-Tac-Toe',
        category: 'BOARD',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 15,
        description: 'Classic 3x3 turn-based grid duel with instant win/draw validation.',
        iconName: 'target',
      },
      {
        id: 'LUDO',
        name: 'Ludo World Arena',
        category: 'BOARD',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 20,
        description: 'Classic 2-4 player board game with server-authoritative dice and tactical tokens.',
        iconName: 'dice',
      },
      {
        id: 'CHESS',
        name: 'Chess Grandmaster',
        category: 'BOARD',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 60,
        description: 'Standard FIDE chess rules with move timers and draw offers.',
        iconName: 'trophy',
      },
      {
        id: 'CHECKERS',
        name: 'Checkers / Draughts',
        category: 'BOARD',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 30,
        description: 'Diagonal jumping and kinging board game duel.',
        iconName: 'gamepad',
      },
      {
        id: 'CONNECT_FOUR',
        name: 'Connect Four',
        category: 'BOARD',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 20,
        description: 'Vertical disc-dropping 4-in-a-row strategy challenge.',
        iconName: 'target',
      },
      {
        id: 'CARROM',
        name: 'Carrom Board',
        category: 'BOARD',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 25,
        description: 'Flick the striker and pocket your carrom men and the queen.',
        iconName: 'target',
      },
      {
        id: 'SNAKES_AND_LADDERS',
        name: 'Snakes & Ladders',
        category: 'BOARD',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 15,
        description: 'Roll the dice, climb ladders, and avoid the treacherous snakes.',
        iconName: 'dice',
      },
      {
        id: 'BACKGAMMON',
        name: 'Backgammon',
        category: 'BOARD',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 30,
        description: 'Ancient tactical checker race with dice roll strategy.',
        iconName: 'dice',
      },
      {
        id: 'REVERSI',
        name: 'Reversi / Othello',
        category: 'BOARD',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 25,
        description: 'Trap opponent discs between your pieces to flip them to your color.',
        iconName: 'target',
      },
      {
        id: 'GOMOKU',
        name: 'Gomoku',
        category: 'BOARD',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 20,
        description: 'Five in a row on a 15x15 Go board.',
        iconName: 'target',
      },
      {
        id: 'BATTLESHIP',
        name: 'Battleship Fleet Command',
        category: 'BOARD',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 25,
        description: 'Call coordinates and sink the enemy fleet in hidden grid naval combat.',
        iconName: 'shield',
      },
      {
        id: 'DOMINOES',
        name: 'Dominoes Duel',
        category: 'BOARD',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 20,
        description: 'Tile-matching game matching identical pip counts.',
        iconName: 'dice',
      },
      {
        id: 'MANCALA',
        name: 'Mancala',
        category: 'BOARD',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 20,
        description: 'Sow seeds into pits and capture the majority into your store.',
        iconName: 'trophy',
      },
      {
        id: 'CHINESE_CHECKERS',
        name: 'Chinese Checkers',
        category: 'BOARD',
        minPlayers: 2,
        maxPlayers: 6,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 25,
        description: 'Hop across the star-shaped board to occupy the opposite corner.',
        iconName: 'target',
      },

      // ----------------------------------------------------------------------
      // Category B: Card Games (Virtual / Non-Monetary Only)
      // ----------------------------------------------------------------------
      {
        id: 'UNO_STYLE',
        name: 'Color Match Clash (UNO-style)',
        category: 'CARD',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 15,
        description: 'Discard cards matching color or number with wild cards and skips.',
        iconName: 'palette',
      },
      {
        id: 'HEARTS',
        name: 'Hearts',
        category: 'CARD',
        minPlayers: 4,
        maxPlayers: 4,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 20,
        description: 'Trick-taking card game avoiding penalty hearts and the Queen of Spades.',
        iconName: 'heart',
      },
      {
        id: 'SPADES',
        name: 'Spades',
        category: 'CARD',
        minPlayers: 4,
        maxPlayers: 4,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 20,
        description: 'Partnership trick-taking card game with bidding.',
        iconName: 'gamepad',
      },
      {
        id: 'RUMMY',
        name: 'Indian Rummy',
        category: 'CARD',
        minPlayers: 2,
        maxPlayers: 6,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 30,
        description: 'Meld cards into valid sequences and sets.',
        iconName: 'gamepad',
      },
      {
        id: 'GIN_RUMMY',
        name: 'Gin Rummy',
        category: 'CARD',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 20,
        description: '2-player rummy variant matching deadwood reduction.',
        iconName: 'gamepad',
      },
      {
        id: 'CRAZY_EIGHTS',
        name: 'Crazy Eights',
        category: 'CARD',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 15,
        description: 'Shed cards on matching suits with wild eights.',
        iconName: 'gamepad',
      },
      {
        id: 'GO_FISH',
        name: 'Go Fish',
        category: 'CARD',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 15,
        description: 'Ask opponents for matching ranks to complete books of four.',
        iconName: 'gamepad',
      },
      {
        id: 'WAR',
        name: 'War Card Duel',
        category: 'CARD',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 10,
        description: 'High card captures cards in classic battle showdowns.',
        iconName: 'gamepad',
      },
      {
        id: 'DURAK',
        name: 'Durak',
        category: 'CARD',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 20,
        description: 'Attack and defend with trump cards to avoid being the fool.',
        iconName: 'shield',
      },
      {
        id: 'PRESIDENT',
        name: 'President / Scum',
        category: 'CARD',
        minPlayers: 3,
        maxPlayers: 6,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 15,
        description: 'Card shedding game climbing the hierarchy ladder.',
        iconName: 'trophy',
      },
      {
        id: 'BLACKJACK',
        name: 'Blackjack (Play Money Only)',
        category: 'CARD',
        minPlayers: 1,
        maxPlayers: 5,
        defaultPlayers: 3,
        supportsSpectators: true,
        turnTimeSeconds: 20,
        description: 'Hit, stand, or double down against the dealer to reach 21 with virtual chips.',
        iconName: 'gamepad',
      },
      {
        id: 'POKER',
        name: 'Texas Hold’em (Play Money Only)',
        category: 'CARD',
        minPlayers: 2,
        maxPlayers: 6,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 30,
        description: 'Virtual-chip social poker with flop, turn, and river community cards.',
        iconName: 'trophy',
      },

      // ----------------------------------------------------------------------
      // Category C: Casual Multiplayer Games
      // ----------------------------------------------------------------------
      {
        id: 'POOL_8_BALL',
        name: '8 Ball Pool Arena',
        category: 'CASUAL',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 30,
        description: 'Pot your solids or stripes and sink the 8 ball to win.',
        iconName: 'target',
      },
      {
        id: 'MINI_GOLF',
        name: 'Mini Golf Battle',
        category: 'CASUAL',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 30,
        description: 'Putt through obstacles and sink the ball in the fewest strokes.',
        iconName: 'flag',
      },
      {
        id: 'AIR_HOCKEY',
        name: 'Air Hockey',
        category: 'CASUAL',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 10,
        description: 'High-speed mallet striking and puck defense table duel.',
        iconName: 'target',
      },
      {
        id: 'DARTS',
        name: 'Darts 501',
        category: 'CASUAL',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 25,
        description: 'Aim with precision to reduce your score from 501 to zero.',
        iconName: 'target',
      },
      {
        id: 'BOWLING',
        name: 'Bowling Strike',
        category: 'CASUAL',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 20,
        description: 'Knock down ten pins in 10 frames of competitive bowling.',
        iconName: 'trophy',
      },
      {
        id: 'TABLE_TENNIS',
        name: 'Table Tennis Duel',
        category: 'CASUAL',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 15,
        description: 'Fast-paced paddle rally with spin and speed controls.',
        iconName: 'target',
      },
      {
        id: 'WORD_SEARCH',
        name: 'Word Search Race',
        category: 'CASUAL',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 60,
        description: 'Find hidden words in the letter grid before time runs out.',
        iconName: 'search',
      },
      {
        id: 'HANGMAN',
        name: 'Hangman Duel',
        category: 'CASUAL',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 20,
        description: 'Guess letters to reveal the secret word with limited lives.',
        iconName: 'gamepad',
      },
      {
        id: 'MEMORY_MATCH',
        name: 'Memory Card Match',
        category: 'CASUAL',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 15,
        description: 'Flip pairs of matching hidden cards to score points.',
        iconName: 'eye',
      },
      {
        id: 'QUIZ_BATTLE',
        name: 'Quiz Battle Arena',
        category: 'CASUAL',
        minPlayers: 2,
        maxPlayers: 6,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 12,
        description: 'Rapid-fire multiple choice trivia across general knowledge.',
        iconName: 'bell',
      },
      {
        id: 'TRIVIA',
        name: 'Trivia Duel',
        category: 'CASUAL',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 15,
        description: '1v1 trivia showdown in sports, history, science, and pop culture.',
        iconName: 'trophy',
      },
      {
        id: 'WORD_BATTLE',
        name: 'Word Scramble Battle',
        category: 'CASUAL',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 30,
        description: 'Form the highest scoring words from seven random tiles.',
        iconName: 'gamepad',
      },

      // ----------------------------------------------------------------------
      // Category D: Fast Competitive Games
      // ----------------------------------------------------------------------
      {
        id: 'REACTION_TEST',
        name: 'Reaction Speed Test',
        category: 'COMPETITIVE',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 5,
        description: 'Tap as fast as humanly possible when the signal turns green.',
        iconName: 'target',
      },
      {
        id: 'ROCK_PAPER_SCISSORS',
        name: 'Rock Paper Scissors',
        category: 'COMPETITIVE',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 10,
        description: 'Best of 3 or 5 simultaneous hand sign duel.',
        iconName: 'gamepad',
      },
      {
        id: 'RPS_TOURNAMENT',
        name: 'RPS Tournament Bracket',
        category: 'COMPETITIVE',
        minPlayers: 4,
        maxPlayers: 8,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 10,
        description: 'Single-elimination bracket tournament of Rock Paper Scissors.',
        iconName: 'trophy',
      },
      {
        id: 'NUMBER_GUESS',
        name: 'Number Guessing Duel',
        category: 'COMPETITIVE',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 15,
        description: 'Guess the hidden secret number with higher/lower hints.',
        iconName: 'target',
      },
      {
        id: 'SPEED_TAP',
        name: 'Speed Tap Rush',
        category: 'COMPETITIVE',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 10,
        description: 'Tap targets across your screen in 10 frantic seconds.',
        iconName: 'target',
      },
      {
        id: 'COLOR_MATCH',
        name: 'Color Match Reflex',
        category: 'COMPETITIVE',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 5,
        description: 'Stroop effect reflex test: match word color vs text meaning.',
        iconName: 'palette',
      },
      {
        id: 'MATH_BATTLE',
        name: 'Speed Math Duel',
        category: 'COMPETITIVE',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 10,
        description: 'Solve arithmetic equations faster than your opponent.',
        iconName: 'target',
      },
      {
        id: 'QUICK_DRAW',
        name: 'Quick Draw Western',
        category: 'COMPETITIVE',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 5,
        description: 'Wait for the bell and draw in sub-millisecond reflexes.',
        iconName: 'target',
      },
      {
        id: 'WORD_SCRAMBLE',
        name: 'Anagram Scramble',
        category: 'COMPETITIVE',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 20,
        description: 'Unscramble jumbled letters into dictionary words.',
        iconName: 'gamepad',
      },
      {
        id: 'TYPING_RACE',
        name: 'Mobile Typing Race',
        category: 'COMPETITIVE',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 45,
        description: 'Type the phrase accurately on mobile keyboard with live WPM tracker.',
        iconName: 'gamepad',
      },

      // ----------------------------------------------------------------------
      // Category E: Strategy & Puzzle Games
      // ----------------------------------------------------------------------
      {
        id: 'SUDOKU_BATTLE',
        name: 'Sudoku Duel',
        category: 'PUZZLE',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 180,
        description: 'Fill 9x9 numbers in a shared grid with error penalties.',
        iconName: 'target',
      },
      {
        id: '2048_MULTIPLAYER',
        name: '2048 Versus Race',
        category: 'PUZZLE',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 120,
        description: 'Slide tiles and merge to 2048 while racing live opponent boards.',
        iconName: 'target',
      },
      {
        id: 'MINESWEEPER_DUEL',
        name: 'Minesweeper Battle',
        category: 'PUZZLE',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 30,
        description: 'Flag mines and clear safe cells with turn steals.',
        iconName: 'shield',
      },
      {
        id: 'CROSSWORD_BATTLE',
        name: 'Mini Crossword Duel',
        category: 'PUZZLE',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 120,
        description: 'Solve across and down clues in a 5x5 speed grid.',
        iconName: 'gamepad',
      },
      {
        id: 'WORDLE_DUEL',
        name: 'Word Guess Duel',
        category: 'PUZZLE',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 60,
        description: 'Guess 5-letter hidden words in 6 tries with colored feedback.',
        iconName: 'target',
      },
      {
        id: 'SEQUENCE',
        name: 'Card Sequence',
        category: 'PUZZLE',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 30,
        description: 'Play cards to place chips and complete 5-in-a-row sequences.',
        iconName: 'target',
      },
      {
        id: 'MASTERMIND',
        name: 'Code Breaker Mastermind',
        category: 'PUZZLE',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 45,
        description: 'Deduce the secret color peg sequence with exact/partial clues.',
        iconName: 'eye',
      },
      {
        id: 'PATTERN_MATCH',
        name: 'Pattern Memory Matrix',
        category: 'PUZZLE',
        minPlayers: 2,
        maxPlayers: 4,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 15,
        description: 'Repeat increasingly long glowing sequences.',
        iconName: 'palette',
      },
      {
        id: 'PUZZLE_DUEL',
        name: 'Jigsaw Puzzle Race',
        category: 'PUZZLE',
        minPlayers: 2,
        maxPlayers: 2,
        defaultPlayers: 2,
        supportsSpectators: true,
        turnTimeSeconds: 120,
        description: 'Assemble puzzle pieces against the clock to complete the art.',
        iconName: 'palette',
      },

      // ----------------------------------------------------------------------
      // Category F: Party & Social Games
      // ----------------------------------------------------------------------
      {
        id: 'WOULD_YOU_RATHER',
        name: 'Would You Rather?',
        category: 'PARTY',
        minPlayers: 2,
        maxPlayers: 8,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 20,
        description: 'Pick between two dilemmas and compare choices with friends.',
        iconName: 'users',
      },
      {
        id: 'TRUTH_OR_DARE',
        name: 'Truth or Dare Social',
        category: 'PARTY',
        minPlayers: 2,
        maxPlayers: 8,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 30,
        description: 'Interactive party questions with photo proof integration.',
        iconName: 'bell',
      },
      {
        id: 'CHARADES',
        name: 'Charades Party',
        category: 'PARTY',
        minPlayers: 3,
        maxPlayers: 8,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 45,
        description: 'Act out words and phrases for your team to guess.',
        iconName: 'users',
      },
      {
        id: 'GUESS_PICTURE',
        name: 'Pixel Reveal Guess',
        category: 'PARTY',
        minPlayers: 2,
        maxPlayers: 6,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 20,
        description: 'Identify the image as tiles slowly disappear.',
        iconName: 'eye',
      },
      {
        id: 'GUESS_WORD',
        name: 'Taboo Word Clue',
        category: 'PARTY',
        minPlayers: 4,
        maxPlayers: 8,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 45,
        description: 'Describe words to teammates without saying the forbidden taboo terms.',
        iconName: 'chat',
      },
      {
        id: 'GUESS_SONG',
        name: 'Name That Tune',
        category: 'PARTY',
        minPlayers: 2,
        maxPlayers: 6,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 15,
        description: 'Listen to short instrumental melodies and guess the song.',
        iconName: 'bell',
      },
      {
        id: 'WHO_AM_I',
        name: 'Who Am I? (Sticky Note)',
        category: 'PARTY',
        minPlayers: 3,
        maxPlayers: 8,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 30,
        description: 'Ask Yes/No questions to deduce the celebrity on your forehead.',
        iconName: 'users',
      },
      {
        id: 'IMPOSTER',
        name: 'The Imposter',
        category: 'PARTY',
        minPlayers: 4,
        maxPlayers: 8,
        defaultPlayers: 6,
        supportsSpectators: true,
        turnTimeSeconds: 60,
        description: 'Everyone receives a secret word except one player. Find the imposter.',
        iconName: 'eye',
      },
      {
        id: 'MAFIA',
        name: 'Mafia / Werewolf',
        category: 'PARTY',
        minPlayers: 5,
        maxPlayers: 10,
        defaultPlayers: 6,
        supportsSpectators: true,
        turnTimeSeconds: 90,
        description: 'Day discussion and night eliminations social deduction game.',
        iconName: 'shield',
      },
      {
        id: 'DRAW_AND_GUESS',
        name: 'Draw & Guess Live',
        category: 'PARTY',
        minPlayers: 2,
        maxPlayers: 8,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 60,
        description: 'Real-time collaborative canvas drawing and chat guessing.',
        iconName: 'palette',
      },
      {
        id: 'PICTIONARY',
        name: 'Pictionary Duel',
        category: 'PARTY',
        minPlayers: 4,
        maxPlayers: 8,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 60,
        description: 'Team vs team quick-sketch guessing challenge.',
        iconName: 'palette',
      },
      {
        id: 'NEVER_HAVE_I_EVER',
        name: 'Never Have I Ever',
        category: 'PARTY',
        minPlayers: 2,
        maxPlayers: 8,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 20,
        description: 'Put a finger down if you have done it; friendly social icebreaker.',
        iconName: 'users',
      },
      {
        id: 'THIS_OR_THAT',
        name: 'This or That',
        category: 'PARTY',
        minPlayers: 2,
        maxPlayers: 8,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 15,
        description: 'Speed voting on everyday preferences with friend compatibility scores.',
        iconName: 'heart',
      },
      {
        id: 'TWO_TRUTHS_AND_A_LIE',
        name: '2 Truths and a Lie',
        category: 'PARTY',
        minPlayers: 2,
        maxPlayers: 6,
        defaultPlayers: 4,
        supportsSpectators: true,
        turnTimeSeconds: 45,
        description: 'Submit three statements; friends vote which one is false.',
        iconName: 'eye',
      },
    ];

    for (const g of list) {
      this.games.set(g.id.toUpperCase(), g);
    }
  }

  public getGame(gameType: string): GameDefinition | undefined {
    return this.games.get(gameType.toUpperCase());
  }

  public getAllGames(): GameDefinition[] {
    return Array.from(this.games.values());
  }

  public getGamesByCategory(category: GameCategory): GameDefinition[] {
    return this.getAllGames().filter((g) => g.category === category);
  }

  public registerEngine(gameType: string, engine: GameEngine): void {
    this.engines.set(gameType.toUpperCase(), engine);
  }

  public getEngine(gameType: string): GameEngine | undefined {
    return this.engines.get(gameType.toUpperCase());
  }
}

export const GameRegistry = new GameRegistryClass();
